### ISSUE TITLE
Crash with Mekanism Community Edition and Universal Tweaks

### ISSUE THREAD

**Issue by redfire75369** [igentuman/EnderStorage-continuation#13]
Crash Report: https://mclo.gs/vi9SB97
Only occurs with 2.6.1 on curseforge. Most likely caused by this commit: https://github.com/igentuman/EnderStorage-continuation/commit/33fed49a05f47eebb1c0967e5efd59469e65e9bf

**Comment by Redfire75369** [comment]
After looking around, it seems this may partially be a Mekanism problem. [https://github.com/Thorfusion/Mekanism-Community-Edition/blob/4e8c389b852ddf15507d64de3c434fc63bcf2fb3/src/main/java/mekanism/common/integration/OreDictManager.java#L487-L489](OreDictManager.java) loops over all 16 metas, as compared to [Thermal Expansion's](https://github.com/CoFH/ThermalExpansion-1.12-Legacy/blob/92b52710c19f3923f81ece2f580b044d8d8111fc/src/main/java/cofh/thermalexpansion/util/managers/machine/SawmillManager.java#L98-L110) using a different method. However, this should still be fixed from this side as well.

**Comment by redfire75369** [comment]
https://github.com/igentuman/EnderStorage-continuation/blob/7e524845a6470cb85e78dce8e736daa90f57e724/src/main/java/codechicken/enderstorage/EnderStorage.java#L54
The config is only loaded in init, which is also where mekanism does its recipe searching, so the `enableAutoCollectItem` is uninitialised when mekanism checks, causing the crash.

**Comment by redfire75369** [comment]
Solved in https://github.com/igentuman/EnderStorage-continuation/commit/1c19007f8999550f0ccf52adfc6f20d9c68a820e
