### ISSUE TITLE
[1.12.2] Game crashes upon launch.

### ISSUE THREAD

**Issue by SonicX8000** [igentuman/EnderStorage-continuation#4]
Minecraft: 1.12.2
Forge: 14.23.5.2860

Mods: 3
CodeChickenLib-1.12.2-3.2.3.358-universal
EnderStorage-1.12.2-2.4.8-universal
HadEnoughItems_1.12.2-4.24.1

Crash:
[crash-2023-03-02_03.36.32-client.txt](https://github.com/igentuman/EnderStorage-continuation/files/10869825/crash-2023-03-02_03.36.32-client.txt)

---

At the title says, the game crashes upon launch when just the above mods added.

**Comment by igentuman** [comment]
This makes no sense

**Comment by igentuman** [comment]
I don't know what happend, but i can reproduce it on 2.4.8, and on 2.4.9 it was fixed somehow
So i'm closing this issue as solved in 2.4.9

**Comment by SonicX8000** [comment]
Yea, can confirm that v2.4.9 no longer crashes upon start up.
