### ISSUE TITLE
A small suggestion regarding the cross dimension toggle.

### ISSUE THREAD

**Issue by Handeril** [igentuman/EnderStorage-continuation#5]
I really do like that this version adds _perDimensionStorage_ as a flag, my suggestion is as simple as instead of _perDimensionStorage_ being just true or false, maybe there could be a "blacklist" or "whitelist" option as well. This could be handy for limiting storage for a single dimension, or only having specific dimensions share a linked storage.

**Comment by igentuman** [comment]
list of dimensions to share storage will conflict with current implementation. This will require lot of changes. 
But i will implement black and white lists where it can works.
