### ISSUE TITLE
Clicking on Liquid Mana in JEI gives empty buckets

### ISSUE THREAD

**Issue by Krutoy242** [igentuman/EnderStorage-continuation#7]
Usually, when you click on liquid, it gives you bucket. If Liquid have no bucket form, JEI should do nothing on click (or at least give liquid block if it exist)

https://user-images.githubusercontent.com/936618/232201806-028b2a16-f36d-4c5c-b0d9-b71a149609ac.mp4

**Comment by igentuman** [comment]
Liquid mana is for internal use only. You shouldn't use it directly

**Comment by Krutoy242** [comment]
I understand its for internal. For internal-use-only items, JEI unallow clicking to obtain this items. For example, Mek Gases - if you klick on them, they not give you empty buckets into inventory.

It would be conventional if clicking on Mana not give anything.
