### ISSUE TITLE
`Push mode` not working propertly

### ISSUE THREAD

**Issue by Krutoy242** [igentuman/EnderStorage-continuation#9]
There is two white tanks, one full and other not
![image](https://github.com/igentuman/EnderStorage-continuation/assets/936618/2902ac49-5d2e-4e71-a694-0a4389996232)

"Desync" reproduce:
1. Place WWW tank in machine to fill it
2. Place other WWW tank in world
3. Set Push Mode and dump to container
4. Now we have two white tanks with fluid and without

https://github.com/igentuman/EnderStorage-continuation/assets/936618/856623ba-0acb-43a2-adbc-f8227bf08530

**Comment by Krutoy242** [comment]
Issue is still actual. Can I hope that the problem will be fixed soon?

**Comment by igentuman** [comment]
Added some checks and forced sync calls.
Now you can't push into tanks with same color and owner.
Liquid won't be visible on client until you activate (right click) tank block.
